version: 2

project_name: modulation

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64

  - id: linux-amd64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        formats: [zip]
    formats: [tar.gz]
    # this name template makes the OS and Arch more readable in the release assets
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - maintainer: Mithun Khatri <mithunkhatri@users.noreply.github.com>
    description: High-performance, cross-platform TUI radio player.
    homepage: https://github.com/mithunkhatri/modulation
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - ffmpeg

brews:
  - name: modulation
    repository:
      owner: mithunkhatri
      name: homebrew-modulation
      token: "{{ .Env.GORELEASER_TOKEN }}"
    directory: Formula
    homepage: https://github.com/mithunkhatri/modulation
    description: High-performance, cross-platform TUI radio player.
    license: MIT
    install: |
      bin.install "modulation"
    dependencies:
      - name: ffmpeg

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
